import React from 'react';
import './CompTwo.css';

const CompTwo: React.FC = () => {
  return (
    <div className="Comp">
      <h3>
        <span role="img" aria-label="Yarn Logo">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dapibus odio at purus pulvinar, ac aliquet ex placerat. Nam condimentum lacus ac tempor cursus. Aliquam in magna nulla. Nunc mollis fringilla turpis porta tristique. Nunc elementum dolor in placerat semper. Fusce elementum dui mauris, nec venenatis est facilisis in. Nunc molestie commodo nisi vel rhoncus. Ut nec finibus velit, eget iaculis mauris. Proin dignissim metus elit, ut convallis nulla imperdiet a. Morbi id blandit libero.

Curabitur et ornare dui. Etiam malesuada faucibus diam, in suscipit ante convallis nec. Donec suscipit tellus sit amet interdum blandit. Nam aliquet vel orci vel maximus. Quisque id interdum felis. Vivamus eget cursus leo. Nunc sagittis id orci rhoncus luctus. Suspendisse dignissim arcu ac quam fringilla gravida.

Proin faucibus auctor turpis, sed tincidunt augue condimentum a. Ut consectetur, lorem ac ornare interdum, odio magna hendrerit nibh, in tristique purus eros eget tellus. Ut sapien tellus, lobortis at tortor vehicula, lacinia scelerisque justo. Vestibulum sit amet faucibus lorem, in sodales nisl. Fusce auctor at lorem vitae fermentum. Maecenas mollis nec nunc ut convallis. Vestibulum eget rutrum mauris. Praesent faucibus nisi feugiat laoreet pharetra. Donec consectetur, nulla eget convallis blandit, arcu ante congue ante, in malesuada arcu arcu et magna. Nam bibendum neque at nisl semper, in sodales leo ultrices. Quisque ante nisl, rutrum non justo nec, posuere venenatis ligula. Phasellus ac ipsum vitae orci malesuada finibus in pretium enim. Nullam sollicitudin dapibus risus sed consectetur. Donec nec posuere lectus. Sed eu arcu eu tortor sodales gravida in non nibh.

Integer varius diam a ipsum sodales, a lacinia dui pharetra. Sed placerat nisi porta, viverra orci eu, hendrerit justo. Cras id neque hendrerit, egestas quam id, sagittis mi. Cras a sem vulputate, ornare leo id, ornare diam. Nulla gravida nisl ac augue pretium, dapibus finibus enim bibendum. Ut tempus dictum nulla vel bibendum. Nulla mollis ut dolor vitae dictum. Nam eu erat vel nisl maximus porta ac at arcu. In hac habitasse platea dictumst. Duis ut purus consequat, vehicula sem vitae, tincidunt odio. Nunc ac tempus diam, quis laoreet massa.

Ut dapibus dui nibh, vel congue leo convallis eu. Ut nec laoreet turpis. Nullam euismod luctus neque, ut aliquet arcu suscipit a. Sed et pretium ante. In hac habitasse platea dictumst. Donec molestie ultrices pharetra. Curabitur orci mauris, lacinia sed congue quis, dapibus ut enim.

Praesent in quam sed tellus commodo elementum. Aliquam interdum est tincidunt turpis vestibulum scelerisque. Nunc bibendum in tortor elementum interdum. Cras et ante tincidunt, luctus sem nec, ultricies neque. Sed quis ante aliquet ex interdum maximus ac in ex. Suspendisse mattis, mi elementum elementum eleifend, elit mi sodales felis, ac ultrices felis urna nec nibh. Cras vitae sapien suscipit tortor faucibus fermentum a sit amet ipsum. Proin et nunc vitae elit feugiat venenatis. Sed quis lacus eget massa tempor elementum eget sed nunc. In eget velit sed elit venenatis efficitur. Pellentesque iaculis dictum dui id elementum. Nulla feugiat, nulla ac pellentesque viverra, dui orci dictum neque, id venenatis sem nulla id sem. In dapibus vel velit et molestie. Nam a lectus elementum, placerat tellus vel, interdum nibh. Integer ornare tortor at faucibus malesuada.

Nunc sollicitudin sem commodo velit condimentum scelerisque. Aliquam tristique quam id justo finibus sollicitudin. Morbi erat mi, elementum ac diam ac, dictum suscipit arcu. Pellentesque elementum elit quis arcu volutpat congue. Fusce nec libero diam. Fusce non sem non nibh ullamcorper dictum. In lectus metus, gravida non pellentesque in, pulvinar sed lorem. Nullam porta, purus et placerat fermentum, tortor nisi tristique ex, a dapibus neque dui sit amet purus. Mauris sed mi non massa maximus egestas. Vivamus a tortor in nibh efficitur tempus sit amet ac sapien. Suspendisse ut dui elit. Curabitur malesuada, diam et ultricies vulputate, justo erat rhoncus neque, id egestas nulla urna vitae leo. Curabitur turpis risus, dignissim sit amet semper eget, imperdiet sed velit. Nam nisi mi, congue at finibus in, aliquam sit amet magna.

Fusce vitae ipsum turpis. Aliquam finibus ultrices tellus ut vestibulum. Cras vel nulla euismod, interdum metus eu, aliquam quam. Maecenas auctor vulputate fermentum. Etiam euismod enim nec nibh tristique tincidunt. Sed sollicitudin risus purus, eget faucibus leo gravida id. Mauris dolor mauris, feugiat a risus non, venenatis pellentesque nibh. Integer ornare tincidunt velit, eu fringilla ipsum congue ut. Pellentesque quis felis augue. Proin in egestas justo, non semper nibh. Suspendisse potenti. Phasellus posuere dui leo, ut iaculis sem placerat in. Mauris eget auctor tortor. Curabitur libero dui, vehicula et molestie at, imperdiet ut velit. Pellentesque malesuada nulla odio, id imperdiet risus pretium nec.

Proin pellentesque vestibulum velit tempor dignissim. Nulla congue, arcu vitae venenatis ullamcorper, nulla magna pellentesque leo, ut eleifend augue augue ut augue. Fusce vitae vehicula ante. In fringilla tincidunt libero ut condimentum. Mauris elit felis, aliquam non tristique sit amet, luctus et erat. Morbi libero risus, porttitor eu bibendum vitae, malesuada sed odio. Cras hendrerit justo eget rutrum dapibus. Proin laoreet lacinia placerat. Phasellus tristique tortor quis suscipit commodo. Pellentesque bibendum cursus nulla, pretium iaculis velit varius vitae. Sed sit amet ultrices magna.

Ut nulla sapien, ultrices id ultrices non, varius quis mi. Aliquam in urna neque. Nulla ullamcorper diam ut augue vestibulum commodo. Cras sit amet justo quis metus ullamcorper consequat. Quisque iaculis tellus risus, sed pharetra eros maximus ac. Etiam convallis neque id dapibus volutpat. Nunc rhoncus varius tellus, viverra molestie est iaculis at. Donec iaculis erat leo, non convallis sem pulvinar nec. In maximus, nisi ac sagittis placerat, orci odio euismod nibh, in tincidunt lectus tellus vitae velit. Donec neque libero, suscipit ac porta eu, viverra sit amet massa. Curabitur mattis, metus ac ornare aliquam, erat tortor scelerisque odio, ac consequat augue tellus ac augue. Ut fringilla bibendum tellus et congue.

Sed elementum, urna id lacinia posuere, ipsum nunc ornare neque, vel mattis quam est quis justo. Suspendisse ornare turpis at mi porta sodales. Proin cursus ultrices nisi et egestas. Ut condimentum eget dolor ut interdum. Suspendisse potenti. Mauris in nulla cursus, congue risus nec, fermentum orci. Vivamus convallis justo pretium volutpat malesuada. Praesent a luctus augue. Cras cursus posuere felis ac accumsan.

Donec viverra pretium felis, nec dapibus risus. Vestibulum congue molestie auctor. Vivamus ornare ac ante sed lobortis. Vestibulum volutpat malesuada faucibus. Maecenas et tortor ligula. Aenean consequat ut est sed volutpat. Nullam a sem et enim auctor pretium. Donec lorem quam, tincidunt at vehicula ac, elementum a nulla. Mauris tincidunt vel purus in semper. Fusce consectetur ullamcorper quam luctus sagittis. Nulla et interdum quam, ac dictum metus. Aenean augue leo, laoreet vitae tempus ac, eleifend sed nunc. Proin ullamcorper tempor justo in euismod. Sed dapibus mi ac magna euismod, in elementum odio tristique. Curabitur molestie lectus nec quam vestibulum, at auctor ligula tristique. Proin id metus eget mauris tincidunt aliquet.

Cras id lacus vulputate, faucibus ligula tempus, malesuada nisi. Etiam nec orci eget ligula tincidunt aliquam. Suspendisse auctor congue ipsum vel aliquet. Sed tincidunt dolor accumsan ante malesuada, cursus facilisis justo varius. Vivamus mattis felis lacus, nec interdum risus posuere volutpat. Etiam dictum faucibus ante sed iaculis. Aliquam porta, massa in lacinia eleifend, dolor purus auctor nulla, gravida ultricies neque nunc ut orci. Duis cursus vitae urna et egestas. Fusce a mattis lectus. Proin commodo fermentum tristique. Nulla volutpat metus quis risus tempus finibus. Mauris lectus turpis, porttitor vitae fermentum vel, commodo quis eros. Cras at ex mi.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras felis velit, egestas nec tortor ac, fermentum elementum mauris. Mauris ut pharetra tortor. Aliquam iaculis magna urna, vel scelerisque leo dignissim vel. Sed et ultrices sapien, sit amet porttitor enim. Nulla placerat id elit id fringilla. Nullam iaculis ornare diam, vel vehicula ipsum aliquet sed. Suspendisse volutpat leo maximus nunc bibendum, vitae pulvinar felis congue. Integer eu arcu vel sapien iaculis pellentesque.

Aliquam mollis non erat ut consectetur. Aenean non elit egestas, sagittis ipsum eu, sodales est. Morbi suscipit velit posuere ipsum tristique, eu pharetra lorem eleifend. Nulla consectetur tristique tellus cursus tincidunt. Pellentesque vulputate, mauris a malesuada scelerisque, sem odio euismod tellus, ac pellentesque dui lacus a erat. Sed id sem tortor. Morbi cursus vel purus ut sagittis. Aenean vestibulum, est ac porta interdum, est magna consectetur ex, sit amet blandit libero erat sed sem. Duis volutpat sodales magna, at dictum orci commodo id. Aenean tempor non nisi sed ullamcorper.

Sed cursus nunc lacus, et fermentum magna rutrum at. Fusce pellentesque interdum orci, at interdum ante commodo sed. Quisque quis accumsan augue. Etiam urna diam, convallis ac rhoncus quis, pulvinar at dolor. Morbi gravida, dui eu dignissim pharetra, risus est maximus risus, vitae placerat sapien enim sit amet ex. Curabitur blandit ipsum a tincidunt bibendum. Curabitur egestas quam ut mi efficitur ornare. Nunc ac porta ligula. Vivamus eget ex hendrerit, interdum nisl et, ultricies ligula. Ut nec ante in tellus placerat tincidunt.

Proin nec mattis est. Etiam nisl nisl, tempus ac nisi faucibus, scelerisque ornare sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis nibh enim, aliquam sed mi id, volutpat vestibulum sem. Morbi ac dolor sit amet libero gravida dictum in non ligula. Nullam consequat pulvinar eros a varius. Vivamus vitae convallis dui, et dictum justo. Donec pulvinar molestie euismod. Sed luctus augue non turpis blandit, in facilisis ipsum finibus. Maecenas pharetra ex sit amet diam elementum gravida. Nulla libero tortor, consectetur sagittis mauris rutrum, pretium sodales massa. Aliquam porta felis at maximus rhoncus. Curabitur dignissim lacus eu varius rhoncus. Aliquam ac elit dapibus, consectetur enim ut, congue nulla. Cras mattis ullamcorper sem non fermentum. Nulla ultricies vel orci ac ullamcorper.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam placerat orci lorem, eget imperdiet dui gravida dignissim. Nunc sem urna, fermentum ac massa sit amet, cursus rhoncus arcu. Duis est odio, dapibus quis iaculis ut, lacinia a urna. Proin vehicula, tortor sit amet sagittis volutpat, tellus libero tristique mi, convallis vestibulum massa elit eu nulla. Proin ultricies dolor lacus, ut volutpat ante laoreet vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus accumsan mollis urna, sed sollicitudin sapien finibus ac. Praesent pharetra tortor faucibus justo venenatis, at auctor urna pharetra. Ut bibendum fringilla quam vitae vulputate.

Etiam pharetra at orci eu rutrum. Integer tempus, ligula vel consequat consequat, lorem ante congue eros, quis volutpat ex dui ac augue. Nam dolor arcu, ultrices sed imperdiet sed, mattis eget ligula. Donec accumsan faucibus fringilla. Curabitur eleifend id erat non imperdiet. Donec velit lorem, fermentum ac rhoncus non, malesuada sed metus. Mauris erat urna, dapibus quis finibus vitae, ultrices placerat nulla. Vestibulum convallis vitae nibh eu suscipit. Duis id augue at dui vestibulum vehicula. Mauris ut dolor sed augue consectetur vehicula. Sed sit amet ullamcorper nulla.

Nullam commodo massa mauris, eu tincidunt tellus mollis vel. Nullam finibus lacus et elementum porttitor. Quisque ut tristique ex, nec cursus lectus. Nulla libero est, posuere a diam et, semper feugiat lorem. Mauris finibus id ipsum id suscipit. Suspendisse erat enim, luctus ut metus tincidunt, semper iaculis risus. Mauris mollis commodo massa sit amet efficitur. Donec sagittis odio et elit feugiat sodales. Mauris sagittis dui nulla, sit amet interdum ex commodo sit amet. Maecenas tincidunt nunc ut augue rutrum pellentesque. Suspendisse ac tellus sit amet metus accumsan varius. Sed eu turpis et nunc consequat luctus eget vel ipsum.

Curabitur eu dictum libero. Integer at magna id dui commodo semper quis a nulla. Ut vitae gravida velit, in scelerisque nunc. Sed sed ipsum ut metus commodo aliquam sit amet id magna. Integer condimentum hendrerit enim. Fusce et nisi lacus. Curabitur interdum eleifend erat, vel porta leo dapibus et. Ut tellus odio, posuere quis porttitor id, facilisis a sem. Phasellus dolor nulla, tristique et sapien sed, sodales imperdiet eros. Mauris ultrices rhoncus urna, et ullamcorper lectus faucibus venenatis. Vestibulum ac cursus tortor. Nunc finibus arcu non dictum tempor. Nam diam magna, varius vitae enim vitae, malesuada mattis massa. Nulla id dignissim odio, elementum lacinia nibh.

Maecenas elementum tempor purus sed feugiat. Cras neque felis, mollis tempus semper vitae, aliquet et est. Nam molestie vestibulum velit vel tristique. Morbi molestie tempor libero et pretium. Nulla in velit quis ante auctor vulputate. Curabitur porttitor maximus orci in mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

In luctus at augue a venenatis. Aenean et porta quam. Sed eu hendrerit sapien, eget iaculis magna. Proin posuere a erat id egestas. Maecenas ornare orci eu libero dictum, sed suscipit quam ornare. Nam nibh velit, varius vel facilisis vitae, ullamcorper sed orci. Nulla purus erat, bibendum at commodo vel, volutpat at est. Donec lacinia nunc tellus, ac facilisis tortor consectetur a. Nam mi arcu, tincidunt id eleifend vel, condimentum quis eros.

Donec ante magna, gravida pulvinar nunc ut, aliquam facilisis nisi. Vivamus rutrum libero ut dictum cursus. Nunc ut blandit sapien, sed egestas enim. Praesent aliquam, nulla ut sagittis commodo, sem enim varius risus, at congue libero elit nec sem. Maecenas tempus mauris elit, ut mollis ligula accumsan a. Praesent libero lectus, consequat eu augue id, tincidunt pellentesque tortor. Aliquam at turpis in leo euismod ultricies eu a dolor. Quisque fringilla sagittis augue. Fusce eu ullamcorper purus. Ut nec tortor lacinia, fermentum nisi ac, elementum velit. Sed sed turpis nibh.

Quisque dictum viverra dolor non pharetra. Mauris vitae ex ac purus condimentum blandit sed vel lacus. In a ullamcorper nibh. Vestibulum in nisi eget lorem dapibus mollis. Donec elementum venenatis turpis sed dictum. Aliquam interdum ultricies orci, et porttitor enim dignissim at. Quisque nunc ante, molestie sit amet consequat sed, bibendum sit amet arcu. Mauris laoreet mauris odio, ac imperdiet enim lobortis vitae. In et molestie purus. Morbi vulputate pulvinar enim, vel sagittis tortor luctus sed. Vestibulum porta vestibulum malesuada. Maecenas faucibus tristique dui, quis lobortis est imperdiet et. Nunc blandit dignissim diam, eu dignissim enim condimentum ac. In nunc velit, suscipit vitae vehicula consectetur, fermentum sed tortor. In hac habitasse platea dictumst. Nulla id scelerisque justo.

Nam convallis eget mi vel hendrerit. Donec placerat leo quis arcu rutrum, eu elementum diam condimentum. In interdum felis odio, nec tempor erat pharetra ac. Nulla porta, lectus eget posuere suscipit, tellus nisl gravida tortor, at molestie nulla purus ac eros. Quisque tristique arcu sed dui vulputate vehicula. Vestibulum sit amet ex ut dolor blandit porta. Proin placerat justo ut quam feugiat, maximus faucibus leo mattis.

Praesent eu elit at ligula laoreet porta. Suspendisse mi dui, finibus in nulla sed, eleifend finibus quam. Cras et ullamcorper risus. Etiam ut risus a enim venenatis fermentum ac quis ante. Quisque id pharetra turpis. Morbi vitae purus consequat, aliquam turpis id, condimentum quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi. Duis mauris nisl, pharetra eget blandit vel, maximus id metus. Duis nisl nisl, lacinia et mattis vel, porttitor eu orci. Mauris nec placerat nibh, quis efficitur nisl. In convallis libero in volutpat laoreet. Cras nec felis suscipit, condimentum nibh id, cursus tellus.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam tincidunt vestibulum ex at bibendum. Quisque sed sem nec lorem commodo sollicitudin id at est. Pellentesque eu ligula varius neque vulputate ullamcorper. Duis eu ligula in enim varius pulvinar. Proin quis lacinia ante. Pellentesque sed consectetur orci. Fusce euismod risus justo, id volutpat ante placerat in. Phasellus pharetra blandit rhoncus. Proin dolor lorem, porta et fringilla a, pellentesque a purus.

Nulla egestas dolor non ipsum rutrum tristique nec vitae ligula. Proin vulputate dignissim nisl, tristique dictum enim ornare eget. Duis et ante sollicitudin, tincidunt magna at, scelerisque leo. Donec pharetra lectus sit amet scelerisque laoreet. Nunc eu tortor tempor, iaculis urna et, suscipit dui. Ut a nisl quis orci volutpat iaculis. Duis ante nulla, tempus maximus pretium vel, placerat sit amet lorem. Mauris vel molestie ipsum. Morbi faucibus tincidunt feugiat. Sed non velit quis arcu pulvinar convallis. Integer sodales ornare lorem, sed malesuada lacus mollis non. Quisque imperdiet, enim ut fringilla porttitor, velit arcu bibendum neque, sit amet vestibulum leo nisl at sem. Mauris odio metus, commodo et massa a, finibus mollis lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Pellentesque tellus elit, mollis ac cursus vitae, dignissim ut purus. Fusce id elit ac dolor sollicitudin efficitur quis non nunc. Mauris hendrerit augue ac tortor elementum, eget viverra purus elementum. Donec tempor sit amet turpis quis viverra. Proin varius diam nec turpis interdum, sit amet lacinia tellus finibus. Curabitur vulputate at ex laoreet pharetra. Ut sed malesuada diam, non mattis nibh. Suspendisse quis sem nec risus gravida pellentesque. Maecenas blandit dui metus, quis mollis tortor aliquet id. Sed iaculis tempor sem ac consequat.
        </span>{' '}
        Comp Two
      </h3>
    </div>
  );
};

export default CompTwo;
